{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ledger-app.serviceAccountName" . }}
  labels:
    {{- include "ledger-app.labels" . | nindent 4 }}
{{- end }}

