{{- if .Values.statefulset.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cockroachdb.serviceAccountName" . }}
  labels:
    {{- include "cockroachdb.labels" . | nindent 4 }}
{{- end }}

